[wokwi]
version = 1
firmware = '.pio/build/stepper-test/firmware.bin'
elf = '.pio/build/stepper-test/firmware.elf'

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"